export const Users = [{
        id: 1,
        profilePicture: "assests/person/1.jpg",
        username: "Daxesh Italiya",
    },
    {
        id: 2,
        profilePicture: "assests/person/2.jpg",
        username: "Yash Shah",
    },
    {
        id: 3,
        profilePicture: "assests/person/3.jpg",
        username: "Mahisha Patel",
    },
    {
        id: 4,
        profilePicture: "assests/person/4.jpg",
        username: "Raj Parmar",
    },
    {
        id: 5,
        profilePicture: "assests/person/5.jpg",
        username: "Vivek Vadodriya",
    },
    {
        id: 6,
        profilePicture: "assests/person/6.jpg",
        username: "Parth Makwana",
    },
    {
        id: 7,
        profilePicture: "assests/person/7.jpg",
        username: "Karansing Zala",
    },
    {
        id: 8,
        profilePicture: "assests/person/8.jpg",
        username: "Viraj Makwana",
    },
    {
        id: 9,
        profilePicture: "assests/person/9.jpg",
        username: "Niraj Hirapara",
    },
];

export const Posts = [{
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assests/post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "assests/post/3.jpg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "assests/post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "assests/post/5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "assests/post/6.png",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "assests/post/7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "assests/post/8.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    }
];